version: '3'

services:
  traefik:
    image: traefik:v2.4
    container_name: proximatic_traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - default
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./conf/config.yml:/config.yml:ro
    command: "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${PROXIMATIC_FQDN}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${PROXIMATIC_ADMIN_USER}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${PROXIMATIC_FQDN}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-secure.service=api@internal"
  api:
    build:
      context: ./api
    container_name: proximatic_fastapi
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proximatic-api.entrypoints=websecure"
      - "traefik.http.routers.proximatic-api.rule=Host(`api.${PROXIMATIC_FQDN}`)"
      - "traefik.http.routers.proximatic-api.tls=true"
      - "traefik.http.routers.proximatic-api.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.proximatic-api-auth.basicauth.users=${PROXIMATIC_ADMIN_USER}"
      - "traefik.http.routers.proximatic-api.middlewares=proximatic-api-auth"

networks:
  proxy:
    external: true

