version: '3'

services:
  traefik:
    image: traefik:v2.4
    container_name: proximatic_traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - default
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./conf/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${PROXIMATIC_FQDN}`)"
      # Protect Traefik Dashboard behind a basic http auth. The user/password string
      # provided with this example file is:
      # username: admin
      # password: dashboard
      # Please change this before you bring up your stack!
      # Generate your own username and password for Traefik Dashboard using this command:
      # echo $(htpasswd -nb <USER> <PASSWORD>) | sed -e s/\\$/\\$\\$/g
      # Then paste the output in the label below as the value for traefik-auth.basicauth.users=
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${PROXIMATIC_ADMIN_USER}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${PROXIMATIC_FQDN}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-secure.service=api@internal"
  backend:
    build:
      context: ./backend
    container_name: proximatic_fastapi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proximatic-backend.entrypoints=websecure"
      - "traefik.http.routers.proximatic-backend.rule=Host(`api.${PROXIMATIC_FQDN}`)"
      - "traefik.http.routers.proximatic-backend.tls=true"
      - "traefik.http.routers.proximatic-backend.tls.certresolver=http"
      - "traefik.http.middlewares.proximatic-backend-auth.basicauth.users=${PROXIMATIC_ADMIN_USER}"
      - "traefik.http.routers.proximatic-backend.middlewares=proximatic-backend-auth"

networks:
  proxy:
    external: true

