http:
  routers:
    mysite:
      entryPoints:
        - "websecure"
      rule: "Host(`mysite.proximatic.link`)"
      middlewares:
        - default-headers
      tls:
        {}
      service: mysite

  services:
    mysite:
      loadBalancer:
        servers:
          - url: "https://www.swanson.link/"
        passHostHeader: false

  middlewares:

    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
